### ISSUE TITLE
Problems when adding a package

### ISSUE THREAD

**Issue by Dan-Crane** [Jerome-Saltmarsh/dart-lemon-engine#4]
Hi)
When adding a dependency to pubspec, I have to write the path to the git directly. Without this action, the error that version 0.5. does not exist occurred.

console:
```txt
Resolving dependencies... 
Because example_lemon depends on lemon_engine 0.5.0 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on lemon_engine: flutter pub add lemon_engine:^0.3.36
```

**Comment by Jerome-Saltmarsh** [comment]
I forgot to publish the latest version, thanks for letting me know. 
 
 The example project probably will break now with the latest version so I will have to fix that too.
