### ISSUE TITLE
delta time

### ISSUE THREAD

**Issue by Dan-Crane** [Jerome-Saltmarsh/dart-lemon-engine#6]
Can you please tell me how do I get the time difference from the past frame?

**Comment by Dan-Crane** [comment]
`engine.durationPerUpdate` has a stream that I can subscribe to and listen to the changes.
```dart
engine.durationPerUpdate.stream.listen((event) {
    time.updateDt(event.inMicroseconds / Duration.microsecondsPerSecond);
});
```

**Comment by Jerome-Saltmarsh** [comment]
You can use the msUpdate value, but that's a good point, I will integrate it into the update function itself as a paremeter

**Comment by Jerome-Saltmarsh** [comment]
durationPerUpdate is what what it aims for and msUpdate is the actual duration since the last frame.

**Comment by Dan-Crane** [comment]
That would be cool:)

**Comment by Dan-Crane** [comment]
I would like to have delta time in both onUpdate and onRender

**Comment by Jerome-Saltmarsh** [comment]
I added it to the onUpdate function (see 0.5.1)

the delta is a double which represents the goal_duration / actual_duration so any physics equations can use that decimal to maintain consistence

**Comment by Jerome-Saltmarsh** [comment]
the renderFunction is a little trickier because it can depend on the settings, if the drawCanvasAfterUpdate flag is true it will render after that, otherwise it might be rendered manually, 

In any case you can still get the duration since the last render with the msRender variable.
